### ISSUE TITLE
Error: Cannot find module 'WorkingDirPath<StartupFile> <ScriptArguments>'

### ISSUE THREAD

**Issue by SlurpTheo** [Microsoft/nodejstools#1509]
##### Expected Behavior 
I should be able to specify both a startup file/script and command-line arguments to that script.

##### Actual Behavior 
The newest Dev Build of NTVS (for VS.2015) gives the error (the subject of this issue). Seems that `'WorkingDirPath<StartupFile> <ScriptArguments>'` is getting passed into npm module resolving as "a" single module itself.

- NTVS Version: https://github.com/Microsoft/nodejstools/releases/tag/v1.3.Dev-03.06.2017
- Visual Studio Version: VS.2015.3
- Node.js Version: 6.10.1
- TypeScript Version: 2.1.6

Reverting to https://github.com/Microsoft/nodejstools/releases/tag/v1.2.RTW got things back working.

##### Steps to Reproduce
1. Have an `*.njsproj` with both `<ScriptArguments>` & a `<StartupFile>` specified.
2. Hit F5 to start debugging.

**Comment by starquake** [comment]
This also happens on Visual Studio 2017 after upgrading to 15.1

**Comment by paulvanbrenk** [comment]
Found the issue this should be fixed in 15.2 and Node 1.3 RTM

**Comment by starquake** [comment]
Is it possible to install a pre-release of either 15.2 or Node 1.3? Or maybe or workaround?

**Comment by paulvanbrenk** [comment]
We haven't put this change in 15.2 yet, but we do expect this to be in the next pre-release. (The other solution is to build the project yourself.)
